In [6]:
x = 1

In [14]:
if 1 > 2:
    message = "if only 1 were greter than two..."
elif 1 > 3:
    message = "elif stands for 'else if'"
else:
    message = "elif all else fails use else (if you want to)"
    parity = "even" if x % 2 == 0 else "odd"
    x = 0
    while x < 10:
        print (x, "is less than 10")
        x+= 1
    for x in range(10):
        print (x, "is less than 10")
    for x in range(10):
        if x == 3:
            continue
        if x == 5:
            break
        print (x)

0 is less than 10
1 is less than 10
2 is less than 10
3 is less than 10
4 is less than 10
5 is less than 10
6 is less than 10
7 is less than 10
8 is less than 10
9 is less than 10
0 is less than 10
1 is less than 10
2 is less than 10
3 is less than 10
4 is less than 10
5 is less than 10
6 is less than 10
7 is less than 10
8 is less than 10
9 is less than 10
0
1
2
4


In [15]:
one_is_less_than_two = 1 < 2
true_equals_false = True == False

x = None
print (x) == None
print (x) is None

None
None


True

In [27]:
import numpy as np

x = [4, 1, 2, 3]
y = sorted(x)
x.sort()
x = sorted([-4, 1, -2, 3], key = abs, reverse = True)
word_counts ={'filipe': 1, 'simão': 2, 'ruben': 3}

wc = sorted(word_counts.items(),
            key = lambda word_count: word_count[1],
            reverse = True)

print(wc)

[('ruben', 3), ('simão', 2), ('filipe', 1)]


In [ ]:
x = sorted([])

In [17]:
!pip install numpy

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/usr/local/opt/python@3.9/bin/python3.9 -m pip install --upgrade pip' command.


In [19]:
import numpy as np #importa a biblioteca numpy e defini-a como np

In [20]:
np.median([1, 2, 3])

2.0

In [23]:
import numpy as np

arr = numpy.array ([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [24]:
print (np.__version__) #mostra a versão do numpy

1.21.4


In [22]:
import numpy as np

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [25]:
import numpy as np

arr = np.array ((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [26]:
arr = np.array(42) #matriz 0-D

print(arr)


42


In [29]:
arr = np.array([1, 2, 3, 4, 5]) #matriz 1-D

print(arr)

[1 2 3 4 5]


In [30]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) #matriz 2-D

print(arr)


[[1 2 3]
 [4 5 6]]


In [31]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) #matriz 3-D

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [32]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [33]:
arr = np.array([1, 2, 3, 4], ndmin=5) #ndimn = 5 define ao array a dimensão 5

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [34]:
arr = np.array([1, 2, 3, 4])

print(arr[0]) #mostra qual é a posição zero no array

1


In [35]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3]) #faz a soma entre a posição numero 2 e 3 do array 

7


In [36]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [37]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [38]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [39]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [40]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [44]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [45]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [46]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [47]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [1]:
!pip install seaborn

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/usr/local/opt/python@3.9/bin/python3.9 -m pip install --upgrade pip' command.


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [3]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [4]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [5]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [6]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [10]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [11]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [12]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [13]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [14]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [15]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [16]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [17]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [18]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [19]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [28]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [29]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [30]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [31]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [32]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [33]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [34]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [35]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [36]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [37]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [38]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [39]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [40]:
arr = np.array([41, 42, 43, 44])

filter_arr = []

for element in arr:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [41]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [45]:
from numpy import random

x = random.randint(100)

print(x)

80


In [46]:
x = random.rand()

print(x)

0.44012627913541924


In [47]:
x=random.randint(100, size=(5))

print(x)

[82 80 29 35 74]


In [48]:
x = random.randint(100, size=(3, 5))

print(x)

[[82 35 44 30 35]
 [73 42 86  9 74]
 [34  8  7 59 44]]


In [49]:
x = random.choice([3, 5, 7, 9])

print(x)

5


In [50]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[3 5 7 5 5 5 7 7 5 7 7 7 3 5 7 5 7 7 7 7 7 7 7 5 5 7 7 7 7 7 7 7 7 7 7 5 3
 5 3 7 7 7 5 5 7 5 5 7 7 7 3 7 7 7 5 5 7 7 7 5 7 7 7 7 5 7 7 7 3 7 5 5 7 7
 5 7 3 7 7 7 7 3 7 3 7 5 7 7 5 7 3 5 7 5 7 7 7 7 7 7]


In [51]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))

print(x)

[[3 7 7 5 5]
 [7 5 3 7 7]
 [5 5 7 7 7]]


In [52]:
arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)

[5 1 2 3 4]


In [53]:
arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))

[5 1 2 4 3]


In [54]:
x = random.normal(size=(2, 3))

print(x)

[[ 0.31603631 -0.5868464   0.69004294]
 [ 1.60242617  0.2379048  -1.53004949]]


In [2]:
from numpy import random

x = random.poisson(lam=2, size=10)

print(x)

[4 0 1 1 1 1 1 5 2 1]


In [3]:
x = random.uniform(size=(2, 3))

print(x)

[[0.02273491 0.98410127 0.28642143]
 [0.80118694 0.52729091 0.98267724]]


In [4]:
x = random.logistic(loc=1, scale=2, size=(2, 3))

print(x)

[[ 1.01630634 -2.47604786  5.90521072]
 [-2.47688242 -2.36373452  5.4027606 ]]


In [5]:
x = random.multinomial(n=6, pvals=[1/6, 1/6, 1/6, 1/6, 1/6, 1/6])

print(x)

[2 2 1 0 0 1]


In [6]:
x = random.exponential(scale=2, size=(2, 3))

print(x)

[[1.05315481 0.76182791 0.11812253]
 [0.10839592 0.89129893 1.3401346 ]]


In [7]:
x = random.chisquare(df=2, size=(2, 3))

print(x)

[[0.25787088 6.12671516 1.26200904]
 [1.73416412 2.60755623 1.22915737]]


In [8]:
x = random.rayleigh(scale=2, size=(2, 3))

print(x)

[[3.25142101 1.68719142 1.37005304]
 [2.20565741 1.36556496 4.39385555]]


In [9]:
x = random.pareto(a=2, size=(2, 3))

print(x)

[[1.378845   1.04779394 0.22033117]
 [0.19923307 0.26246978 0.27536248]]


In [10]:
x = random.zipf(a=2, size=(2, 3))

print(x)

[[ 2  1  9]
 [ 1 68  1]]


In [13]:
even_numbers = [x for x in range(5) if x % 2 == 0]
squares      = [x * for x in range(5)]
even_squares = [x * x for x in even_numbers]
square_dict = {x : x * x for x in range(5)}
square_set  = {x * x for x in [1, -1]} 
zeroes = [0 for _ in even_numbers]pairs = [(x, y)
         for x in range(10)
         for y in range(10)]
increasing_pairs = [(x, y)
         for x in range(10)
         for y in range(x + 1, 10)]

SyntaxError: invalid syntax (1250501640.py, line 2)

In [14]:
# Importando a biblioteca de matematica
import math

# Importando a biblioteca de aleatoriedade
import random

# Inicialmente, não temos nenhum ponto 'dentro' do circulo
pontos_no_circulo = 0

# Não sorteamos também nenhum ponto
pontos_sorteados = 0

# Sortearemos então, 10.000 pontos

for i in range(10000):
    # Incrementamos o numero de pontos sorteados
    pontos_sorteados = pontos_sorteados + 1.0

    # Sorteando dois pontos x e y
    # A função uniform sorteia numeros com casas decimais
    x = random.uniform(-1, 1)
    y = random.uniform(-1, 1)

    # Calculando a distancia do ponto x, y com a origem
    # A função 'hypot' da biblioteca math calcula a distancia euclidiana
    distancia = math.hypot(x, y)

    # Verificamos, entao, se a distancia encontrada
    # é compatível com nosso criterio de aceitação (<= 1)
    if distancia <= 1:
        pontos_no_circulo = pontos_no_circulo + 1.0

# Finalmente, depois de sorteados os pontos, calculamos a razão
razao_entre_total = pontos_no_circulo / pontos_sorteados

# A estimativa de pi vai ser 4 vezes esse valor
pi_estimado = 4 * razao_entre_total

# Imprimimos a estimativa
print(pi_estimado)

3.144
